# Generated by Django 5.0.6 on 2024-11-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
